### ISSUE TITLE
How were straight strokes, circles and triangles generated?

### ISSUE THREAD

**Issue by tmquan** [hzwer/LearningToPaint#12]
Thanks for your nice work, 

I am just wondering, for simple strokes like (flat) circles, triangles, rectangles, do we really need the renderer since we already have simpler state representation? For example, the circle only needs a center and a radius instead of a 10-value state vector.

**Comment by hzwer** [comment]
Yes, you can design different representations with fewer parameters. In fact, some of my simpler renderers have some action dimensions that are discarded.

**Comment by tmquan** [comment]
Hi @hzwer , 

I would like to revisit this issue for a comparison between strokes and geometry primitive like rectangles or circles. 
May I ask can you further provide the code for your these pre-trained models? 
In addition, the normalize function in 
https://github.com/hzwer/LearningToPaint/blob/master/baseline_modelfree/Renderer/stroke_gen.py 
does not seem to be like normalization in the range (0~1), what is its purpose by the way?

Thanks for your attention and hope that you can help to clarify those points.

**Comment by hzwer** [comment]
I have provided some pre-trained models, see README.
The normalization is performed by the Sigmoid activation function before the output of networks.
