### ISSUE TITLE
Renderer input features

### ISSUE THREAD

**Issue by tmquan** [hzwer/LearningToPaint#14]
Hi @hzwer , 
Could you clarify the input feature of the neural renderer as it is 10-value vector or 13-value vector (+RGB). 
If training with 10-value vector, how the painter can generate color pictures?

Bests,

**Comment by hzwer** [comment]
The renderer uses a 10-dimentional vector to generate grayscale strokes. The agent multiplies the other 3-dimentional action by the grayscale image to generate colorful images.

**Comment by AhmedAkram96** [comment]
hi @hzwer **Thank you for the great work in the paper and the code !**
I have a question that is a little bit related to this issue.

I'm trying to render the output actions of the agent (actor) in the learning to paint project using  the fluid renderer of spiral ( https://github.com/deepmind/spiral ), So the issue I'm currently facing is understanding the specific meaning of the agent output actions parameters, so I can map it to to the input actions of the other renderer. 
I understand  that the last 3 parameters are for the RGB; However, **I'm not sure I understand how the first 10 parameters represent the shape, position and transparency?**
