### ISSUE TITLE
Output strokes per iteration only.

### ISSUE THREAD

**Issue by jwb95** [hzwer/LearningToPaint#15]
Hi,
thank you for your work.

I am struggling to modify the code so that, when running `python3 baseline/test.py --max_step=80 --actor=actor.pkl --renderer=renderer.pkl --img=path_to_image --divide=5`, it generates images with only the strokes added during the latest iteration - instead of the sum of all strokes.

Do you have an idea on this?

Thank you

**Comment by hzwer** [comment]
Hello, 
    Please look at line 51 in test.py, you can save color_stroke[:, i].

**Comment by jwb95** [comment]
Thank you for quick and effective response.

I managed to achieve what I wanted by inserting `save_img(color_stroke[:,i], args.imgid)` at line 51 in test.py and modifying the `save_img`-function to save the single strokes in a separate folder.
