### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by ThisIsIsaac** [hzwer/LearningToPaint#17]
noticed some typos in your paper:

1. equation 3 has a hanging paranthesis in the very right 

> `V(s_t) = r(s_t, a_t) + γV(s_t1))`

suggested fix:

> `V(s_t) = r(s_t, a_t) + γV(s_t1)`

2. on page 5, the first sentence of the last paragraph,
> The neural renderer network is consisting of several fully connect layers and convolution layers

suggested fix:

> The neural renderer network is consisting of several fully connected layers and convolution layers

Hope it helps :)

**Comment by hzwer** [comment]
Thank you for reading carefully, we have modified the paper and we will submit the updated version next month.

**Comment by ThisIsIsaac** [comment]
Great!

Have you tried spectral normalization GAN & adding L1 distance to WGAN loss?
