### ISSUE TITLE
Would you please provide download link in Baidu netdisk?

### ISSUE THREAD

**Issue by Chrysler2016** [hzwer/LearningToPaint#20]
Hi, Hzwer,
      Would you please provide download link of these render.pkl and actor.pkl with a Baidu netdisk share? As you know, google is not easy to access from China. Thanks.

**Comment by hzwer** [comment]
链接: https://pan.baidu.com/s/1GELBQCeYojPOBZIwGOKNmA 提取码: aq8n 
done

**Comment by Chrysler2016** [comment]
Thank you very much.
